on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Semantic release
    steps:
      - name: Semantic Release
        uses: yriahi/semantic-release-action@v1
        with:
          extra_plugins: |
            @semantic-release/changelog@6.0.0
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    