on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Semantic release
    steps:
      # checkout code base
      - name: Checkout
        uses: actions/checkout@v3      
      
      - name: Setup Node.js with GitHub Package Registry
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'
          scope: 'y.riahi'
      
      # semantic release
      - name: Semantic Release
        # uses: yriahi/semantic-release-action@v1
        uses: ./
        with:
          extra_plugins: |
            @semantic-release/changelog@6.0.0
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Publish To GitHub Package Registry
        if: steps.semantic.outputs.new_release_published == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
